import React from 'react'

export const metadata = {
  title:'Supernova - Services',
  description:'Generated by Next.js',
}

const page = () => {

  
  return (
    <div>
      services
    </div>
  )
}

export default page
