import React from 'react'

export const metadata = {
  title:'Supernova - Lets get in touch',
  description:'Generated by Next.js',
}


const page = () => {
  return (
    <div>
      Contact us
    </div>
  )
}

export default page
