import React from 'react'
import Contact from '@/components/Contact'

export const metadata = {
  title:'Supernova - Lets get in touch',
  description:'Generated by Next.js',
}


const page = () => {
  return (
    <div>
      <Contact />
    </div>
  )
}

export default page
