import AboutUs from '@/components/AboutUs'
import React from 'react'

export const metadata = {
  title:'Supernova - About us',
  description:'Generated by Next.js',
}

const page = () => {
  return (
    <div>
      <AboutUs />
    </div>
  )
}

export default page
