import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Hero from "@/components/Hero";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title:'Supernova - Event Planners',
  description:'Generated by Next.js',
}



export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        <Hero />
        {children}
      </body>
    </html>
  );
}
