import React from 'react'

export const metadata = {
  title:'Supernova - Gallery',
  description:'Generated by Next.js',
}

const page = () => {
  return (
    <div>
      Gallery Photos
    </div>
  )
}

export default page
