import Error from '@/components/Error'
import React from 'react'

export const metadata = {
  title:'Supernova - Gallery',
  description:'Generated by Next.js',
}


const page = () => {
  return (
    <div>
        <Error />
    </div>
  )
}

export default page
